### PR TITLE
RENO-2325: Page Container Layout

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2325)

**This PR does the following:**
- Removes DS "layout" classes in favor of local app layout using Grid. Longer term we should switch back to DS, but DS needs to rework its layout component.
- Fixes the right sidebar width issue on iPad.
- Fixes the alignment order of sections on mobile. (sidebar goes below main content).

### Review Steps:
- [ ] Check online resources pages
- [ ] Check location finder page

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr156-pmktimb3nxy7posp6hqkt2qyjlo6ivdv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ff4e9380afb06bd94aadd4

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr156-pmktimb3nxy7posp6hqkt2qyjlo6ivdv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ff4e9380afb06bd94aadd4

**Review by misselbeck — APPROVED** [review]
Looks good! Works across all window sizes. Content collapses as expected. No more weird sizes with the sidebar.

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr156-pmktimb3nxy7posp6hqkt2qyjlo6ivdv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60ff4e9380afb06bd94aadd4

**Pull request merged**
