### PR TITLE
RENO-2017+2018: Online Resources MultiSelect Filters

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[RENO-2017](https://jira.nypl.org/browse/RENO-2017)
[RENO-2018](https://jira.nypl.org/browse/RENO-2018)

**This PR does the following:**
- RENO-2018: Add MutliSelect Filters to Online Resources
- RENO-2017: Adds "Core Resource" Logic to Online Resource Card.

#### RENO-2017: "Core Resource" Badge Logic

Goto:
[https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa/research/collections/online-resources/search](https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa/research/collections/online-resources/search)

- [ ] From the "Subjects" filter select "Historical Newspapers"
- [ ] After the search updates, the top 2 results should be "Fulton Search: Historical newspapers" and "Newspapers.com"
- [ ] Both of these results should have the "Core Resource" badge in top left, other search results on the pg should not have this badge.

#### RENO-2018: MultiSelect Filters

Goto: [https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa/research/collections/online-resources/search](https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa/research/collections/online-resources/search)

- [ ] Try different MultiSelect filters and combinations, and buttons.
- [ ] Url should update each time filters are saved and Search results should update.

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr148-iqnh0zvdrw6d2tjsqnddfvvwqrqaxhcv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60f1e803742468dbd26168dc

**Review by misselbeck — APPROVED** [review]
Generally works really well. Only a couple of issues noted that will be spun off into separate tickets:

- If I select a “top-level” subject, I would expect the results to include all child subjects, as well. But I don’t get “Fulton” returned if I select “Reference & Resource Types”…only when I drill-down and select “Historical Newspapers.”
- Having trouble with the Availability selector. Two examples….

Selecting “New York City History” as a subject, and selecting “Library Card Required”
(should not return Brooklyn Historical Society Newspapers)

Selecting “Kids” as the audience, and selecting “On Site Access Only”
(should not return BrainPop)

**Pull request merged**
