### PR TITLE
RENO-2876: Subjects json:api

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2876)
[Metronome](http://themetronome.co/components/XXX/?fresh=true)

**This PR does the following:**
-

### Review Steps:
- [ ] Example step one

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr266-qyj5fyp2t7itzp4y1emzfscbnhqnccvx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ca42dd9027707d3f4ce36

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr266-qyj5fyp2t7itzp4y1emzfscbnhqnccvx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ca42dd9027707d3f4ce36

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr266-qyj5fyp2t7itzp4y1emzfscbnhqnccvx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ca42dd9027707d3f4ce36

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr266-qyj5fyp2t7itzp4y1emzfscbnhqnccvx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ca42dd9027707d3f4ce36

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr266-qyj5fyp2t7itzp4y1emzfscbnhqnccvx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ca42dd9027707d3f4ce36

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr266-qyj5fyp2t7itzp4y1emzfscbnhqnccvx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/624ca42dd9027707d3f4ce36

**Comment by nypl-wluisi** [comment]
@isastettler Lets review this together on our call this afternoon.

**Review by isastettler — APPROVED** [review]
Super cool stuff!

**Pull request merged**
