### PR TITLE
RENO-223: Online Resources: Build Featured Resources Page (T-90)

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-223)
[Figma](https://www.figma.com/file/CCCdFt8H7pMqHjkRQlivSw/IA---Templates-%2B-Components?node-id=41669%3A321)

**This PR does the following:**
- Builds the "Featured Resource" Detail Pg

### Review Steps:
- [ ] Goto this preview env url: https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa/research/online-resources
- [ ] Under "Featured Resources" click "Homework Help" link, you should goto the search pg, filtered by this particular "resource topic" and the url should be `/research/online-resources/featured/homework-help`
- [ ] Enter a search query into the search and hit submit, the search should be "reset" and you'll see a search for your search term only, ignoring any "resource topic" filtering from the previous step.

### Front End Review Steps:
- [ ] View [Preview Enviornment](ttps://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa/research/online-resources)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Review by knezmilos — APPROVED** [review]
Looks good to me

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr139-dratzn0i5sndh2n7qjl2gynlwlis2grk.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60b9621b3e5c644655a44b8b

**Pull request merged**
