### PR TITLE
RENO-2742: Add 404 Pg

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2742)

**This PR does the following:**
- Adds a basic 404 page to Scout, replacing the NextJS default. This is setup for slug pages which use Drupal CMS for routing, as well as routes that only exist in NextJS.

### Review Steps:
- [ ] A&D Featured Resource: https://pr244-fzo6g2v3sh3ive1tlpeejzuthpwvrifw.tugboat.qa/research/collections/articles-databases/featured/slug-that-doesnt-exist
- [ ] A&D Slug: https://pr244-fzo6g2v3sh3ive1tlpeejzuthpwvrifw.tugboat.qa/research/collections/articles-databases/slug-that-doesnt-exist
- [ ] Blog Slug: https://pr244-fzo6g2v3sh3ive1tlpeejzuthpwvrifw.tugboat.qa/blog/slug-that-doesnt-exist
- [ ] Generic: https://pr244-fzo6g2v3sh3ive1tlpeejzuthpwvrifw.tugboat.qa/page-that-doesnt-exist

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr244-fzo6g2v3sh3ive1tlpeejzuthpwvrifw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622bbb008884bf8cd4aed79f

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr244-fzo6g2v3sh3ive1tlpeejzuthpwvrifw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622bbb008884bf8cd4aed79f

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr244-fzo6g2v3sh3ive1tlpeejzuthpwvrifw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622bbb008884bf8cd4aed79f

**Review by isastettler — APPROVED** [review]
Lots of tests here too! I'll make suer to add this to the press release pages too

**Pull request merged**
