### PR TITLE
RENO-2212: Request Visit Form Submit Handling

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2212)

**This PR does the following:**
- Adds submit handling for Locations Local Request a Visit Form
- Adds 2 new env variables for `SENDGRID_API_KEY` and `SENDGRID_EMAIL_ENABLE`

**Sendgrid Setup Instructions**

Set the `DRUPAL_API` .env variable to point to this env: `https://treasures-d8.nypl.org`
You can get the sendgrid api key from the D9 backend, go here: [https://treasures-d8.nypl.org/admin/config/system/phpmailer-smtp](https://treasures-d8.nypl.org/admin/config/system/phpmailer-smtp) under "SMTP AUTHENTICATION" > "password" field

Set this as the value for `SENDGRID_API_KEY` .env variable.
To control whether or not the emails send, set the `SENDGRID_EMAIL_ENABLE` — use either true or false

**D9 Setup Instructions/Content Entry**
The email address this form submits to comes from the library "email" field. For example, to test emails are working, you can first set your email address here on this node: https://treasures-d8.nypl.org/node/41/edit and then when you fill out the form, select "53rd Street Library" from the select list.

### Review Steps:
- [ ] Pull in latest code; run npm install
- [ ] Set .env variables for emails
- [ ] Goto http://localhost:3000/locations/request-visit

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr191-hpa0zgdgaweyq83ulnpgjrsbcmt5ig4i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617ab1806d8bf79843883d81

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr191-hpa0zgdgaweyq83ulnpgjrsbcmt5ig4i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617ab1806d8bf79843883d81

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr191-hpa0zgdgaweyq83ulnpgjrsbcmt5ig4i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617ab1806d8bf79843883d81

**Comment by misselbeck** [comment]
- Form validation and submit all checked out, as expected.
- I noticed that if the location email was not set in the CMS, you get an ugly error. So maybe add a fallback email that can catch the online request just in case?

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr191-hpa0zgdgaweyq83ulnpgjrsbcmt5ig4i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617ab1806d8bf79843883d81

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr191-hpa0zgdgaweyq83ulnpgjrsbcmt5ig4i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617ab1806d8bf79843883d81

**Review by misselbeck — APPROVED** [review]

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr191-hpa0zgdgaweyq83ulnpgjrsbcmt5ig4i.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617ab1806d8bf79843883d81

**Pull request merged**
