### PR TITLE
RENO-2319+RENO-2339: Online Resources Detail Pg VQA & Search for Scholarly Journals Page

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[RENO-2319](https://jira.nypl.org/browse/RENO-2319)
[RENO-2339](https://jira.nypl.org/browse/RENO-2339)

**This PR does the following:**
- VQA Cleanup for Online Resources Detail Pages
- Adds breadcrumbs as a prop for PageContainer and updates all app pages with dynamic breadcrumbs.
- RENO-2339: Adds generic pg for "Find E-Journals and Scholarly E-books by Title in Databases"

### Review Steps:
- [ ] Review Online Resources Detail Pg: https://pr157-rfqadhhglseotybln3xgdmlwdmvx9r7q.tugboat.qa/research/collections/online-resources/jstor
- [ ] Review Other pages breadcrumbs: https://pr157-rfqadhhglseotybln3xgdmlwdmvx9r7q.tugboat.qa/research/collections/online-resources
- [ ] Review "Find E-Journals and Scholarly E-books by Title in Databases" pg: https://pr157-rfqadhhglseotybln3xgdmlwdmvx9r7q.tugboat.qa/research/collections/online-resources/find-journals-title-databases

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr157-rfqadhhglseotybln3xgdmlwdmvx9r7q.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61009cb980afb05c804b9313

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr157-rfqadhhglseotybln3xgdmlwdmvx9r7q.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61009cb980afb05c804b9313

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr157-rfqadhhglseotybln3xgdmlwdmvx9r7q.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61009cb980afb05c804b9313

**Review by misselbeck — APPROVED** [review]
This looks like it hits all the VQA items that were spread across:
RENO-2319, RENO-2322, RENO-2325.

Only item to note there, is that on RENO-2319...these two instructions kind of cancel each other out...so am going to assume the current layout is approved. Just for reference:

**VQA Individual Resources**
- Spacing between bottom of card and top of bottom rail menu should be 32px
- Increase spacing between bottom of right sidebar and top of footer to 32px.

With the way the CSS Grid is laid out, only the latter would apply above, as on the individual resource page, the right menu will always be longer the bottom of the card.

(confirmed that they both have the correct 2rem bottom margin, though)

**RENO-2339: Search for Scholarly Journals Page**
- Looks good to me...ship it!

**Pull request merged**
