### PR TITLE
RENO-2379:  Change Copy and Paths To Articles & Databases

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2379)

**This PR does the following:**
- Changes "Online Resources" name/copy to "Articles & Databases"
- Updates path structure from `/research/collections/online-resources` ->`/research/collections/articles-databases`
- Adds some misc cleanup for google analytics and metatags

### Review Steps:
- [ ] Review preview env here: https://pr170-xvuyhayusycsl7dqmbvcwmf0mtty63bv.tugboat.qa/research/collections/articles-databases

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr170-xvuyhayusycsl7dqmbvcwmf0mtty63bv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6112b13eb52cf974ffb737c6

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr170-xvuyhayusycsl7dqmbvcwmf0mtty63bv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6112b13eb52cf974ffb737c6

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr170-xvuyhayusycsl7dqmbvcwmf0mtty63bv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6112b13eb52cf974ffb737c6

**Review by misselbeck — COMMENTED** [review]
Does this line need to be updated to the new URL scheme?

https://github.com/NYPL/dxp-react-search/blob/ce8669f7d424a55ba00c8795dd0ac7ff86b24f71/src/components/online-resources/SidebarMenus/content.js#L8

Super minor....but how about the two aria labels on the search form?
https://github.com/NYPL/dxp-react-search/blob/ce8669f7d424a55ba00c8795dd0ac7ff86b24f71/src/components/online-resources/SearchForm/SearchForm.js#L107

Does this test needs updating, as well?
https://github.com/NYPL/dxp-react-search/blob/ce8669f7d424a55ba00c8795dd0ac7ff86b24f71/src/components/online-resources/OnlineResourceCard/OnlineResourceCard.test.js#L12

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr170-xvuyhayusycsl7dqmbvcwmf0mtty63bv.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6112b13eb52cf974ffb737c6

**Review by misselbeck — APPROVED** [review]
LGTM!

**Pull request merged**
