### PR TITLE
RENO-2236+RENO-2239: Online Resources: Card Grid & Search Results Skeleton Loaders

### PR DESCRIPTION
**Pull request by knezmilos**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2236)

**This PR does the following:**
- Adds a CardGridSkeleton loader to replace the Skeleton loader in ResourceTopics and MostPopularResources components

### Review Steps:
- [ ] Review example

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr146-n8miweccy0tedqkkgv1qpt6paea5rmql.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e72cee462cdf82db995d05

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr146-n8miweccy0tedqkkgv1qpt6paea5rmql.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e72cee462cdf82db995d05

**Review by nypl-wluisi — CHANGES_REQUESTED** [review]
@knezmilos This is looking great so far. One thing I noticed is there's a conflict with the CSS added here and the location finder loading skeleton, you can see it here: https://pr146-n8miweccy0tedqkkgv1qpt6paea5rmql.tugboat.qa/locations

Not entirely sure what's getting picked up

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr146-n8miweccy0tedqkkgv1qpt6paea5rmql.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e72cee462cdf82db995d05

**Comment by knezmilos** [comment]
@nypl-wluisi, conflict with the location finder loading skeleton is resolved.
SearchResultsSkeleton component is added to this branch.

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr146-n8miweccy0tedqkkgv1qpt6paea5rmql.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e72cee462cdf82db995d05

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr146-n8miweccy0tedqkkgv1qpt6paea5rmql.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60e72cee462cdf82db995d05

**Review by nypl-wluisi — APPROVED** [review]

**Pull request merged**
