### PR TITLE
RENO-2187 - Switch Hero to Use React DS Hero 5050

### PR DESCRIPTION
**Pull request by knezmilos**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2187)

Preview env
https://pr134-4tsdwqfmdbanlkxbzbbcdtfrofpe9ivd.tugboat.qa/locations

**This PR does the following:**
- Switches the local Hero component to use DS Hero 5050 component.

### Review Steps:
- [ ] Pull in latest code
- [ ] Review example

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by knezmilos** [comment]
@nypl-wluisi, switching the hero component looks to be working fine.  I've only needed to add padding to the "hero__content" class locally because the DS component removes padding for 960px and larger sizes, not exactly sure why, perhaps that's something that can be looked at.
Image passed to the component in this case is wrapped in a div with a "hero__image" class since the image in this case is an svg.

**Review by nypl-wluisi — CHANGES_REQUESTED** [review]
This looks good so far. Can you also try to remove the styles from Hero.scss? Ideally none of those would be needed, since the styles are provided by the DS, but some overrides might be necessary.

**Comment by knezmilos** [comment]
I'll work on removing styles from Hero.scss.  I think we'd just need to keep the style for the svg size.  
If we remove the styles, is the display as in the attached screenshots acceptable? The Hero component image size is set to max width of 50%, however for smaller images, the text on the right will be wider.

Screen Shot 2021-05-18 at 3 01 10 PM
Screen Shot 2021-05-18 at 3 01 19 PM

**Comment by knezmilos** [comment]
@nypl-wluisi, most of the local styles are removed, only left is setting the link color to white and the padding around the "hero__content" container.  That's something that can possibly be changed in DS.
Let me know what you think.

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr134-4tsdwqfmdbanlkxbzbbcdtfrofpe9ivd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60a525e13e5c64cfef99089a

**Pull request closed without merging**
