### PR TITLE
RENO-2836: Fixes for pageContainer and menus

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2829)

**This PR does the following:**
- Adds breadcrumb title to `/locations/request-visit` pg
- Fixes heading level for sidebar menu to set h3
- Fixes heading level for bottom rail menu on `research/collections/articles-databases`
- Fixes responsiveness of bottom rail menu on `research/collections/articles-databases` and `/locations`

### Review Steps:
- [ ] Pull in latest code `git fetch && git checkout page-containers-cleanup-2022-03-14`
- [ ] Start app `npm run dev`
- [ ] Check above mentioned pages for various changes

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr246-098rvkhy9o5cnkvqtp153han4c9tlzfz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622ff76ebce4cc1c7355966c

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr246-098rvkhy9o5cnkvqtp153han4c9tlzfz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622ff76ebce4cc1c7355966c

**Review by isastettler — COMMENTED** [review]
I think it might be great to add a margin between menus. Looking at [figma ](https://www.figma.com/file/CCCdFt8H7pMqHjkRQlivSw/IA---Templates-%2B-Components?node-id=41669%3A321) designs it seems to be set so that the Menu title should have `margin 11px 0px` and the menu container `margin: 10px 0 px`. 
In ds-prototypes/Menu/Menu.modules.css is a class .vertical with `margin-bottom: 2rem` set for vertical menus only. However the vertical menu for [press release](https://www.figma.com/file/CCCdFt8H7pMqHjkRQlivSw/IA---Templates-%2B-Components?node-id=51980%3A91984) has the same margin as the mobile vertical menu (as mentioned above). Maybe here would be a good place to make the changes?

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr246-098rvkhy9o5cnkvqtp153han4c9tlzfz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622ff76ebce4cc1c7355966c

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr246-098rvkhy9o5cnkvqtp153han4c9tlzfz.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622ff76ebce4cc1c7355966c

**Pull request merged**
