### PR TITLE
RENO-1651: DS 0.14.0 Upgrade && Fixes for W3 Validation Errors

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](http://jira.nypl.org/browse/RENO-1651)
[Metronome](http://themetronome.co/components/XXX/?fresh=true)

**This PR does the following:**
- fixes W3 validation errors related to "button icon" component having `aria-describeby` prop
- upgraded `@nypl/design-system-react-components` 0.11.0 => 0.14.0
- removed next-transpile-modules since DS handles es5 bundle now for IE11

**TO DO**
- Fix css issues related to DS upgrade (mm)
- Fix any new IE11 issues (mm)

### Review Steps:
- [ ] Example step one

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by misselbeck** [comment]
- Set the content model to box-sizing: border-box. I saw this was the default in D8. It solved a lot of the spacing and overflow issues.
- There is a bug in the wrapper mixin of the DS that reverses the media query logic of the padding calc. I updated that mixin local here to the app, also put in place an override to elements where that mixin is applied upstream in the DS. I'll open a bug fix issue there, and when it is updated we can remove the override locally.
- Where possible, I let the DS styles apply to most elements, removing local style overrides that didn't seem necessary

**Comment by nypl-wluisi** [comment]
@misselbeck This looks great. Just a few small things left to fix.

On Desktop views, the width of the autosuggest dropdown should match the width of the input:
autosuggest-width

Similar on iPad:

autosuggest-ipad-width

The "Open Now" checkbox appears to have lost its styling and alignment:

open-now-checkbox

If you compare it to production: https://www.nypl.org/locations

**Comment by misselbeck** [comment]
For the "Open Now" checkbox, shouldn't the Design System control the styling and appearance?

https://nypl.github.io/nypl-design-system/storybook-static/?path=/story/checkbox--basic-checkbox

Or do you want to override that style manually in the app to make the checkbox larger, etc? Doesn't that somewhat defeat the purpose? I'm fine either way, but just wanted to confirm.

**Comment by nypl-wluisi** [comment]
@misselbeck For the "open now" checkbox we can just override it in our app as we did before, and circle back later to trying to get it into the design system. We're trying to get this PR released to prod ASAP because it fixes accessibility issues. So we'll have more time after this PR is released to discuss the checkbox with the DS team.

**Comment by nypl-wluisi** [comment]
@misselbeck These fixes look great. Just 2 more small things I noticed:

- Can you fix the alignment of the components for IE11? Mainly the "Search Header" and the "Bottom Promo" component, for some reason they have no max-width.
- iPhone 5 (320px wide) the Search button should be on the same line as the form input. Right now its on its own line.

**Comment by misselbeck** [comment]
@nypl-wluisi 

I adjusted the search form for small screen sizes.

I can't seem to replicate the IE11 alignment issue for the components you mentioned. Due to the way IE handles svg, the Grab & Go logo has some extra space on each side, but the other components line up. I'm using a Windows 7 VM. Here is what I see....

ie11-search-header

ie11-bottom-promo

**Comment by nypl-wluisi** [comment]
@misselbeck I'm using Browserstack Windows 8.1 IE11 (Latest) and this is what I see:

Find your Library component:
find-your-lib-ie11

Bottom Promo component:
bottom-promo-ie11

I sent you an invite to Browserstack awhile back, we have a free account for the reno team w/ 5 seats. Let me know if you need me to resend.

**Comment by misselbeck** [comment]
@nypl-wluisi 

Thanks for the Browserstack invite. I got it up and running. It is a very handy tool.

I still can't seem to replicate that issue in the screenshot. Here is what I'm seeing:

ie11-browserstack

And here is the bottom promo....

ie11-browserstack-bottom

Windows 8.1 IE11 (Latest)

Maybe we need to collab via a screenshare?

**Pull request merged**
