### PR TITLE
RENO-2251: Hero Changes

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2251)

**This PR does the following:**
- Preview Env: https://pr144-a8x6e8imggt5de0p4ev57cjv0hlolg9s.tugboat.qa/locations
- Updates hero to use post-covid lion logo and copy
- Updates bottom promo to use new post-covid links, images, and copy

### Review Steps:
- [ ] https://pr144-a8x6e8imggt5de0p4ev57cjv0hlolg9s.tugboat.qa/locations

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr144-baweujkbmwx2girvsqnx03r7iesj3ov3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db3c8357072d4424e6a74c

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr144-baweujkbmwx2girvsqnx03r7iesj3ov3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db3c8357072d4424e6a74c

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr144-a8x6e8imggt5de0p4ev57cjv0hlolg9s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db3f16f543e77f5865e219

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr144-a8x6e8imggt5de0p4ev57cjv0hlolg9s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db3f16f543e77f5865e219

**Review by knezmilos — APPROVED** [review]

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr144-a8x6e8imggt5de0p4ev57cjv0hlolg9s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60db3f16f543e77f5865e219

**Pull request merged**
