### PR TITLE
RENO-2174: Online Resources: Build OnlineResourceCard Component

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2174)
[Preview Env](https://pr142-0qhyqyxjkkbw7g0l0rt6jw4cm8il50ys.tugboat.qa/research/collections/online-resources/search?alpha=all)

**This PR does the following:**
-

### Review Steps:
- [ ] Example step one

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr142-0qhyqyxjkkbw7g0l0rt6jw4cm8il50ys.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c803f8cde720e31c7efba8

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr142-0qhyqyxjkkbw7g0l0rt6jw4cm8il50ys.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c803f8cde720e31c7efba8

**Comment by misselbeck** [comment]
- adds 'collapsible' prop to the OnlineResourceCard component
- pulls in Button and related components from the DS (note: I am trying to use the design system styles for consistency...they don't quite match the Figma comp)
- sets some basic className logic and related CSS styles for hide-and-show functionality

**Comment by nypl-wluisi** [comment]
@misselbeck This looks great so far. Can you make sure the component looks correct on tablet and mobile views? I think the main issue now is the "Library Card Required" status badge on mobile has some spacing issues.

**Comment by misselbeck** [comment]
- adjusted the spacing for statusBadge and bottom links for mobile + tablet

Note: I noticed that the right sidebar appears on tablet (min-width 600px) at 25% width. This looks like a little tight to me, and is not in the Figma design...BUT this is how the Design System handles it, so I am hesitant to override that.

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr142-0qhyqyxjkkbw7g0l0rt6jw4cm8il50ys.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60c803f8cde720e31c7efba8

**Comment by nypl-wluisi** [comment]
@misselbeck This looks great in terms of the OR Card Component, so I'm going to approve and merge this now. Thanks for flagging the right sidebar issue. I'll create a new jira ticket to discuss w/ UX.

**Pull request merged**
