### PR TITLE
Tugboat QA Test

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](http://jira.nypl.org/browse/RENO-XXX)
[Metronome](http://themetronome.co/components/XXX/?fresh=true)

**This PR does the following:**
-

### Review Steps:
- [ ] Example step one

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-twc3imqmex4hylgamrujbb19eieswfkl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-iyzwiz7vekqde2reqdhcohb8xabn4wth.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-znvadpbpnpwiniwylrzddd5o6iank5ct.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-znvadpbpnpwiniwylrzddd5o6iank5ct.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-znvadpbpnpwiniwylrzddd5o6iank5ct.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-znvadpbpnpwiniwylrzddd5o6iank5ct.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-znvadpbpnpwiniwylrzddd5o6iank5ct.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr107-znvadpbpnpwiniwylrzddd5o6iank5ct.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604fe6c6437dd11943ed3371

**Comment by nypl-wluisi** [comment]
@EdwinGuzman When you get a chance, take a look at this. This is all I had to setup for Preview Environments using Tugboat QA. It's a little quirky for NodeJS apps, but it works. So it's just 1 .yml config file for Tugboat and then I set environment variables via their dashboard. 

You can see the env here: https://pr107-znvadpbpnpwiniwylrzddd5o6iank5ct.tugboat.qa/locations

**Comment by EdwinGuzman** [comment]
Looks simple enough. Was it easier than Vercel?

The app itself doesn't work and I'm assuming it's because of CORS issues?

**Comment by nypl-wluisi** [comment]
About the same as Vercel. The only tricky part was the way you have to run `npm start` on Tugboat using runit, otherwise the build never knows its finished. The issue with the app you had was the Refinery was still powered down (QA turns off overnight), so the app should work now.

**Pull request closed without merging**
