### PR TITLE
RENO-2329: Accessibility QA Fixes

### PR DESCRIPTION
**Pull request by nypl-wluisi**
[Jira Ticket](https://jira.nypl.org/browse/RENO-2329)

**This PR does the following:**
- Fixes Multiple ID issue on Search Results and Online Resource Card
- Changes "Filter By" from H3 to H2
- Removes Button from AlphabetNav and just uses anchor links

### Review Steps:
- [ ] Review the app on preview env here: https://pr159-bkxg5gh9dohuc1jj5mv8a8cyqm8oaqrp.tugboat.qa/research/collections/online-resources

### Front End Review Steps:
- [ ] View [Example](http://localhost:3000/)

### CODE REVIEW

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-bkxg5gh9dohuc1jj5mv8a8cyqm8oaqrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6102f4ca331d46e42853baf2

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-bkxg5gh9dohuc1jj5mv8a8cyqm8oaqrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6102f4ca331d46e42853baf2

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-bkxg5gh9dohuc1jj5mv8a8cyqm8oaqrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6102f4ca331d46e42853baf2

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-bkxg5gh9dohuc1jj5mv8a8cyqm8oaqrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6102f4ca331d46e42853baf2

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-bkxg5gh9dohuc1jj5mv8a8cyqm8oaqrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6102f4ca331d46e42853baf2

**Comment by nypl-wluisi** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr159-bkxg5gh9dohuc1jj5mv8a8cyqm8oaqrp.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6102f4ca331d46e42853baf2

**Review by misselbeck — APPROVED** [review]
This all looks good. Made a couple minor adjustments:
- Removed the hover style for the inactive AlphaNav link (coming from the DS)
- Update to the 'aria-disabled' label as prompted by the console

**Pull request merged**
